# 1 Exercise : Numpy practice

## 1. Choose a value and set the variable x to that value. 

## 2. What is command to compute the square of x? Its cube? 

In [1]:
import numpy as np

In [2]:
 import scipy.linalg as la

In [3]:
import matplotlib.pyplot as plt 

In [6]:
x=81
np.square(x)

6561

In [10]:
np.power(x,3)

531441

## 3. Choose an angle θ and set the variable theta to its value (a number). 


## 4. What is sinθ? cosθ? Angles can be measured in degrees or radians. Which of these are being used ?

In [37]:
theta=45
np.sin(theta)

0.8509035245341184

In [38]:
np.cos(theta)

0.5253219888177297

## 5. Use the np.linspace function to create a row vector called meshPoints containing exactly 500 values with values evenly spaced between -1 and 1. 

In [41]:
mesh=np.linspace(-1,1,num=500)
mesh

array([-1.        , -0.99599198, -0.99198397, -0.98797595, -0.98396794,
       -0.97995992, -0.9759519 , -0.97194389, -0.96793587, -0.96392786,
       -0.95991984, -0.95591182, -0.95190381, -0.94789579, -0.94388778,
       -0.93987976, -0.93587174, -0.93186373, -0.92785571, -0.9238477 ,
       -0.91983968, -0.91583166, -0.91182365, -0.90781563, -0.90380762,
       -0.8997996 , -0.89579158, -0.89178357, -0.88777555, -0.88376754,
       -0.87975952, -0.8757515 , -0.87174349, -0.86773547, -0.86372745,
       -0.85971944, -0.85571142, -0.85170341, -0.84769539, -0.84368737,
       -0.83967936, -0.83567134, -0.83166333, -0.82765531, -0.82364729,
       -0.81963928, -0.81563126, -0.81162325, -0.80761523, -0.80360721,
       -0.7995992 , -0.79559118, -0.79158317, -0.78757515, -0.78356713,
       -0.77955912, -0.7755511 , -0.77154309, -0.76753507, -0.76352705,
       -0.75951904, -0.75551102, -0.75150301, -0.74749499, -0.74348697,
       -0.73947896, -0.73547094, -0.73146293, -0.72745491, -0.72

## 6. What expression will yield the value of the 53th element of meshPoints? What is this value? 

In [42]:
mesh=np.array(np.linspace(-1,1,num=500))
x=np.array([53])
print(mesh[x])

[-0.78757515]


# Vector and matrix operations: Exercise 

## 1. You can multiply vectors by constants. Compute vec2 = (np.pi/4) * vec1 

In [42]:
vec1 = np.array([-1,4,-9]) 
mat1 = np.array([[1,3,5],[7,-9,2],[4, 6, 8]])
vec2 =(np.pi/4) * vec1 
vec2

array([-0.78539816,  3.14159265, -7.06858347])

## 2.The cosine function can be applied to a vector to yield a vector of cosines. 

In [17]:
vec2 = np.cos(vec2)
vec2

array([ 0.70710678, -1.        ,  0.70710678])

## 3. You can add vectors and multiply by scalars. Compute 

In [18]:
vec3 = vec1 + 2 * vec2 
vec3

array([ 0.41421356,  2.        , -7.58578644])

## 4. The Euclidean norm of a matrix or a vector is available using la.norm. 

In [20]:
la.norm(vec3)

7.855935892848037

## 5. You can do row-column matrix multiplication. Compute the product of mat1 and vec3 and set vec4 equal to the result. 

In [22]:
vec4=mat1*vec3
vec4

array([[  0.41421356,   6.        , -37.92893219],
       [  2.89949494, -18.        , -15.17157288],
       [  1.65685425,  12.        , -60.6862915 ]])

## 6. Compute the transpose of mat1.

In [23]:
np.transpose(mat1)

array([[ 1,  7,  4],
       [ 3, -9,  6],
       [ 5,  2,  8]])

## 7. Compute the determinant of mat1. 

In [27]:
la.det(mat1)

161.99999999999997

## 8. Compute the trace of mat1. 

In [26]:
np.trace(mat1)

0

## 9. Find the smallest element in vec1.

In [29]:
np.min(vec1)

-9

## 11. What expression would you use to find the smallest element of the matrix mat1

In [30]:
np.min(mat1)

-9

## 12. The function np.random.rand can be used to construct and fill vectors and matrices with random numbers. Use the help facility in Python to learn how to construct a 10 × 10 matrix named M filled with random numbers. 

In [43]:
m=np.random.rand(10,10)
np.mat(m)

matrix([[0.69879017, 0.79243757, 0.01770034, 0.85093359, 0.53527686,
         0.1518969 , 0.4683515 , 0.31669167, 0.90941081, 0.44741347],
        [0.65645573, 0.86260206, 0.58451674, 0.83189884, 0.87032463,
         0.34241321, 0.04312371, 0.58616078, 0.09091688, 0.45466072],
        [0.53655892, 0.75475851, 0.84022364, 0.77391475, 0.08595951,
         0.03582291, 0.5948336 , 0.07737675, 0.73951699, 0.13699431],
        [0.99585124, 0.92133126, 0.56868563, 0.48016971, 0.43616688,
         0.7225001 , 0.35270188, 0.74045921, 0.85485883, 0.8041814 ],
        [0.18996122, 0.6646684 , 0.79705787, 0.8218892 , 0.77886981,
         0.94526535, 0.88507237, 0.51971601, 0.36305768, 0.51119879],
        [0.25341336, 0.53602892, 0.94891129, 0.08511544, 0.74366492,
         0.47911779, 0.48235278, 0.03321657, 0.37040642, 0.84921701],
        [0.09270317, 0.98063636, 0.6059452 , 0.83191632, 0.2862277 ,
         0.91587818, 0.31710637, 0.67624194, 0.89715038, 0.92218098],
        [0.45980846, 0.7396