## 1. Write a python program to take a 3X3 matrix as a user input. Convert the matrix into numpy array. Print the matrix, rank, shape of the matrix.

In [1]:
import numpy as np

In [4]:
mat=[[int(input()) for x in range(3)] for y in range(3)]

1
2
3
4
5
6
7
8
9


In [13]:
np.matrix(mat)

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [24]:
np.shape(mat)

(3, 3)

In [25]:
np.linalg.matrix_rank(mat)

2

## 2. Write a function that generates 10 integers and use it to build an array 

In [42]:
np.random.randint(10,size=(10))

array([9, 0, 8, 4, 3, 0, 7, 6, 2, 4])

## 3. Create a random vector (1D array) of size 10 and sort it 

In [44]:
sort=np.random.randint(10,size=(10))
sort

array([9, 2, 5, 5, 3, 8, 4, 0, 4, 8])

In [46]:
sorted(sort)

[0, 2, 3, 4, 4, 5, 5, 8, 8, 9]

##   4. Write a Python program to generate five random numbers from the normal distribution. 

In [49]:
np.random.normal(5,size=5)

array([3.38858256, 3.86822317, 4.06416556, 5.30261403, 2.6237942 ])

## 5. Write a numpy program program to add and subtract two random matrices. The size of the matrix will a user input. All the matrix element should be a positive integer value. Suppose  'A' and 'B' are two matrix. All the value of 'A' matrix cannot be greater than 10 and values of 'B' matrix cannot be greater than 20. 

In [1]:
import numpy as np

In [2]:
x=int(input())
y=int(input())
a=np.random.randint(10,size=(x*y))
b=np.random.randint(20,size=(x*y))
c=np.reshape(a,(x,y))
mat1=np.matrix(c)
print(mat1)
d=np.reshape(b,(x,y))
mat2=np.matrix(d)
print(mat2)

2
2
[[4 2]
 [0 2]]
[[6 6]
 [2 3]]


In [4]:
add=mat1+mat2
add

matrix([[10,  8],
        [ 2,  5]])

In [5]:
sub=mat1-mat2
sub

matrix([[-2, -4],
        [-2, -1]])

## 6. Write a numpy program program to multiply two random matrices. The size of the matrices will a user input. All the matrix element should be a positive integer value. Suppose 'A' and 'B' are two matrix. All the value of 'A', 'B' matrices  cannot be greater than 10.

In [10]:
x=int(input())
y=int(input())
a=np.random.randint(10,size=(x*y))
b=np.reshape(a,(x,y))
mat1=np.matrix(b)
print(mat1)
i=int(input())
j=int(input())
c=np.random.randint(10,size=(i*j))
d=np.reshape(c,(i,j))
mat2=np.matrix(d)
print(mat2)


1
2
[[4 0]]
2
3
[[6 9 0]
 [4 0 8]]


In [11]:
mat1*mat2

matrix([[24, 36,  0]])