# Exercise 1: How to replace items that satisfy a condition with another value in numpy array? 
Replace all odd numbers in arr with -1

In [2]:
import numpy as np

In [4]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]) 
arr2 = np.where(arr%2==1,-1,arr)
arr
arr2


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

# Exercise 2: How to reshape an array? (2 Points) 
Convert a ID array to a 2D array with 2 rows 

In [33]:
arr = np.arange(10)
arr
np.reshape(arr,(2,-1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# Exercise 3: How to generate custom sequences in numpy without hardcoding? 
Create the following pattern without hardcoding. Use only numpy functions and the below input array 

In [37]:
arr =np.array([1,2,3])
np.r_[np.repeat(arr,3),np.tile(arr,3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

# Exercise 4: How to get the common items between two python numpy arrays? 
Get the common items between a and b 

In [42]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

# Exercise 5: How to get the positions where elements of two arrays match? 
Get the positions where elements of a and b match 

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

# Exercise 6: How to create a 2D array containing random floats between 5 and 10? 
Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10. 

In [47]:
arr=np.random.uniform(5,10,size=(5,3))
arr

array([[5.77523248, 7.78135374, 8.28519012],
       [9.14465367, 6.00203055, 6.23078272],
       [9.95825838, 7.94388165, 9.11065406],
       [9.48440021, 7.1261099 , 7.64945842],
       [7.96435048, 9.91628045, 9.53299713]])

# Exercise 7: How to limit the number of items printed in output of numpy array to 6? 
Limit the number of items printed in python numpy array a to a maximum of 6 elements.

In [57]:
a=np.arange(15)
np.set_printoptions(threshold=6)
a


array([ 0,  1,  2, ..., 12, 13, 14])

# Exercise 8: How to pretty print a numpy array by suppressing the scientific notation (like 1el0)? 
Limit the number of items printed in python numpy array a to a maximum of 6 elements. 

In [60]:
np.random.seed(100)
arr = np.random.random([3,3])/1e3
arr

array([[5.43404942e-04, 2.78369385e-04, 4.24517591e-04],
       [8.44776132e-04, 4.71885619e-06, 1.21569121e-04],
       [6.70749085e-04, 8.25852755e-04, 1.36706590e-04]])

# Exercise 9: How to swap two columns in a 2d numpy array? 
Swap columns 1 and 2 in the array arr. 

In [71]:
arr=np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
arr[:,[1,0,2]]  #swapping column

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

# Exercise 1 0: How to swap two rows in a 2d numpy array? 
Swap rows 1 and 2 in the array arr:

In [78]:
arr = np.arange(9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [79]:
arr[[1,0,2],:]

array([[3, 4, 5],
       [0, 1, 2],
       [6, 7, 8]])