# 1.Multiply the two matrices.

In [15]:
import numpy as np

In [4]:
x=[[1,2,3],[3,5,6],[6,7,9]]

In [6]:
print(np.mat(x))

[[1 2 3]
 [3 5 6]
 [6 7 9]]


In [8]:
y=[[1,2,5,12],[6,7,3,0],[4,7,9,11]]

In [10]:
print(np.mat(y))

[[ 1  2  5 12]
 [ 6  7  3  0]
 [ 4  7  9 11]]


In [13]:
result=np.dot(x,y)

In [8]:
print(result)

[[ 25  37  38  45]
 [ 57  83  84 102]
 [ 84 124 132 171]]


# 2. Extract all numbers divisible by 3 from the array

In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12])
arr1=arr[(arr%3==0)]
arr1
arr1[(arr1!=0)]

array([ 3,  6,  9, 12])

# 3. How to get the unique common items between two python numpy arrays?

In [ ]:
import numpy as np

In [8]:
a=np.array([1,2,3,2,3,4,3,4,5,6])

In [9]:
b=np.array([7,2,10,2,7,4,9,4,9,8])

In [10]:
print(a,b)

[1 2 3 2 3 4 3 4 5 6] [ 7  2 10  2  7  4  9  4  9  8]


In [11]:
np.intersect1d(a,b)

array([2, 4])

# 4. How to remove from one array those items that exist in another?

In [135]:
a = np.array([1,2,3,4,5,11,22,33,44,55])
b = np.array([5,6,7,8,9,10,11])
a[~np.in1d(a,b)]

array([ 1,  2,  3,  4, 22, 33, 44, 55])

# 5. How to get the positions where elements of two arrays match?

In [46]:
import numpy as np

In [9]:
arr1 = np.array([1,2,3,2,3,4,3,4,5,6])
arr2 = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(arr1==arr2)


(array([1, 3, 5, 7], dtype=int64),)

# 6. How to create a 2D array containing random floats between 10 and 25?

In [12]:
np.random.uniform(10,25,size=(5,3))

array([[17.79747269, 12.43633467, 24.12441954],
       [14.2946037 , 23.91065992, 19.71443985],
       [12.30603147, 12.0773444 , 10.06689599],
       [16.62974504, 13.24584241, 21.4615344 ],
       [12.42770719, 20.70035032, 24.08139899]])

# 7. Take a string as input. Create a new string that is the reverse of the first string.

In [122]:
a='hello'[::-1]
a

'olleh'

# 8. Write a Python program to remove the first occurrence of a specified element  (ex 7 ) from an array.

In [1]:
import numpy as np

In [32]:
arr=np.array([1,2,7,2,7,8,7,5,5,2,5,7,7,7])
arr

array([1, 2, 7, 2, 7, 8, 7, 5, 5, 2, 5, 7, 7, 7])

In [33]:
np.where(arr==7)
np.delete(arr,np.where(arr==7))

array([1, 2, 2, 8, 5, 5, 2, 5])

In [1]:
#10

## 10. Write a Python program to find the occurrences of 10 most common words in a given text.

In [2]:
from collections import Counter

In [3]:
txt="A language's standard library is often treated as part of the language by its users, although the designers may have treated it as a separate entity. Many language specifications define a core set that must be made available in all implementations, in addition to other portions which may be optionally implemented. The line between a language and its libraries therefore differs from language to language."

In [4]:
split_it=txt.split()

In [5]:
Counter=Counter(split_it)

In [8]:
most_occur=Counter.most_common(10)

In [9]:
print(most_occur)

[('language', 4), ('a', 3), ('treated', 2), ('as', 2), ('the', 2), ('its', 2), ('may', 2), ('be', 2), ('in', 2), ('to', 2)]


## Do the same for words which are at least 4 characters long.



In [22]:
import re

In [23]:
txt="A language's standard library is often treated as part of the language by its users, although the designers may have treated it as a separate entity. Many language specifications define a core set that must be made available in all implementations, in addition to other portions which may be optionally implemented. The line between a language and its libraries therefore differs from language to language."

In [40]:
print(re.findall(r"b\w{4,}\b",txt))

['brary', 'between', 'braries']


## 11. Create a python program to generate the Fibonocci series. 

In [41]:
limit=int(input("how many terms?"))

how many terms?10
