In [5]:
import numpy as np

In [6]:
#list & array
list = [[1,2,2],[2,5,6]]
list

[[1, 2, 2], [2, 5, 6]]

In [7]:
array1=np.array(list)
array1

array([[1, 2, 2],
       [2, 5, 6]])

In [8]:
list +10     #### Error

TypeError: can only concatenate list (not "int") to list

In [9]:
array1 + 10

array([[11, 12, 12],
       [12, 15, 16]])

In [10]:
array1

array([[1, 2, 2],
       [2, 5, 6]])

In [11]:
array2=array1.astype('float')
array2


array([[1., 2., 2.],
       [2., 5., 6.]])

In [12]:
array1.mean(axis=0)

array([1.5, 3.5, 4. ])

In [13]:
a9=np.full((2,3),7)                   #creates a scalar matix

In [14]:
a9

array([[7, 7, 7],
       [7, 7, 7]])

In [15]:
a9=np.eye(3)                           #Creates identity matrix

In [20]:
a9

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
a11=np.random.randn(2,1)
print(all)

<built-in function all>


In [18]:
import numpy as np
a=np.random.randn(2,1)
print(a)

[[0.25493767]
 [0.06537455]]


In [21]:
a11=np.random.random((3,2))

In [22]:
a11

array([[0.74189695, 0.83646317],
       [0.77917574, 0.236355  ],
       [0.7033426 , 0.92403965]])

In [23]:
import numpy as np

In [24]:
a1=np.array(range(15))
a2=np.array([[-5,3],[10,4]])

In [25]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [26]:
a2

array([[-5,  3],
       [10,  4]])

In [27]:
a3=np.array([[5,6],[0,-1]])

In [28]:
a3

array([[ 5,  6],
       [ 0, -1]])

In [29]:
a6=np.subtract(a3,a2)

In [30]:
a6

array([[ 10,   3],
       [-10,  -5]])

In [31]:
a8=np.add(a3,a2)

In [32]:
a8

array([[ 0,  9],
       [10,  3]])

In [33]:
a9=np.multiply(a2,a3)

In [34]:
a9

array([[-25,  18],
       [  0,  -4]])

In [35]:
a10=np.divide(a3,a2)

In [36]:
a10

array([[-1.  ,  2.  ],
       [ 0.  , -0.25]])

In [37]:
x = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
print(x)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [38]:
#With Slicing create a subarray consisting of the first 2 rows
y = x[1:3, 1:3]
print(y)


[[ 6  7]
 [10 11]]


In [39]:
x[0, 0] = 77     # Changing the value
print(x)          # Replaced by "77"


[[77  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [40]:
#An Example to show  Mixing integer indexing with slices yields an array of lower rank,

a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
row_r1 = a[0, :2]    # Rank 1 view of the second row of a
row_r2 = a[1:2, :]  # Rank 2 view of the second row of a
print(a)
print()
print(row_r1, row_r1.shape)  # Prints "[5 6 7 8] (4,)"
print(row_r2, row_r2.shape)  # Prints "[[5 6 7 8]] (1, 4)"



[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[1 2] (2,)
[[5 6 7 8]] (1, 4)


In [41]:
# We can make the same distinction when accessing columns of an array:
col_r1 = a[:, 1]
col_r2 = a[:, 0]

print(col_r1, col_r1.shape)  # Prints "[ 2  6 10] (3,)"
print()
print(col_r2, col_r2.shape)


[ 2  6 10] (3,)

[1 5 9] (3,)


In [42]:
#Array Indexing programs
# Create a new array from which we will select elements
a = np.array([[10,20,30], [44,55,66], [27,28,29], [40, 41, 42]])
print(a)


[[10 20 30]
 [44 55 66]
 [27 28 29]
 [40 41 42]]


In [43]:
#a = np.array([[10,20,30], [44,55,66], [27,28,29], [40, 41, 42]])
#print(a)

# Create an array of indices
b = np.array([0, 2, 0, 1]) # Select one element from each row of a using the indices in b
print(a[np.arange(4), b])

[10 66 27 41]


In [44]:
a = np.array([[1,2], [3, 4], [5, 6]])
bool_id = (a > 2)   # Find the elements of a that are bigger than 2;

print(a)
print(bool_id)          #creates resultant boolean array


[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [45]:
# Examples for Reading and writing array on the file
 
a = np.array(['a','b','c']) 
np.save('Indu.npy',a)
b = np.load('Indu.npy') 
print(b)


['a' 'b' 'c']


In [46]:
#a1 = np.array(['a','b','c']) 
a = np.array(range(8)) 
np.savetxt('Numpy03.txt',a) 
#np.savetxt('Numpy03.txt',a1) 
b = np.loadtxt('Numpy03.txt') 
print(b)


[0. 1. 2. 3. 4. 5. 6. 7.]


Copy and view in numpy

In [47]:
a = np.array(range(6)) 
print(a)  

print( 'Applying id() function: ') 
print (id(a))  
print()

print ('a is assigned to b:' )
b = a 
print(b)  
print()
print ('b has same id():') 
print (id(b))  
print()
print ('Change shape of b:') 
b.shape = (3,2 )
print (b)  
print()
print ('Shape of a also gets changed:') 
print (a)
print()

# To begin with, a is 3X2 array 
a = np.array(range(8)).reshape(4,2)
print(a)  
print()
print('Create view of a:') 
b = a.view() 
print(b)  
print()
print ('id() for both the arrays are different: ') 
print ('id() of a: ')
print(id(a))  
print()
print ('id() of b: ') 
print (id(b))  

# Change the shape of b. It does not change the shape of a 
b.shape = (2,4) 

print('Shape of b: ') 
print (b)  
print()
print('Shape of a: ') 
print (a)

#Create a new array for deep copy
print()
a = np.array([[10,10], [2,3], [4,5]]) 
print(a)  

print ('Create a deep copy of a:' )
b = a.copy()
print()
print ('Array b is:') 
print(b)  

#b does not share any memory of a 
print ('Can we write b is a') 
print(b is a)  
b[0,0] = 100 

print ('updated array b:') 
print (b)  

print ('a remains unchanged:') 
print (a)


[0 1 2 3 4 5]
Applying id() function: 
2667649992464

a is assigned to b:
[0 1 2 3 4 5]

b has same id():
2667649992464

Change shape of b:
[[0 1]
 [2 3]
 [4 5]]

Shape of a also gets changed:
[[0 1]
 [2 3]
 [4 5]]

[[0 1]
 [2 3]
 [4 5]
 [6 7]]

Create view of a:
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

id() for both the arrays are different: 
id() of a: 
2667649992304

id() of b: 
2667649992544
Shape of b: 
[[0 1 2 3]
 [4 5 6 7]]

Shape of a: 
[[0 1]
 [2 3]
 [4 5]
 [6 7]]

[[10 10]
 [ 2  3]
 [ 4  5]]
Create a deep copy of a:

Array b is:
[[10 10]
 [ 2  3]
 [ 4  5]]
Can we write b is a
False
updated array b:
[[100  10]
 [  2   3]
 [  4   5]]
a remains unchanged:
[[10 10]
 [ 2  3]
 [ 4  5]]


In [48]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'PackageLoader', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_distributor_init', '_globals', '_import_tools', '_mat', '_mklinit', 'abs', 'absolute', 'ab

In [49]:
#Universal functions
np.sqrt([0,1,4,9,16,25,36,49,64,81,100])


array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [50]:
np.sin([0,1,45,90,180,270,360])

array([ 0.        ,  0.84147098,  0.85090352,  0.89399666, -0.80115264,
       -0.17604595,  0.95891572])

In [51]:
np.tanh([45,225])

array([1., 1.])

In [52]:
np.tan([45,225])

array([ 1.61977519, -2.53211499])

In [53]:
np.cos(range(10))

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026])

In [54]:
np.floor([-1,-2.5,-4.7,-0.7,-5.1])

array([-1., -3., -5., -1., -6.])

In [55]:
np.ceil([-1,-2.5,-4.7,-0.7,-5.1])

array([-1., -2., -4., -0., -5.])

In [56]:
np.floor([3.5,6.1,9.9,8.1,6.8])

array([3., 6., 9., 8., 6.])

In [57]:
np.ceil([3.5,6.1,9.9,8.1,6.8])

array([ 4.,  7., 10.,  9.,  7.])

In [58]:
np.exp([0,2,5,7,8])

array([1.00000000e+00, 7.38905610e+00, 1.48413159e+02, 1.09663316e+03,
       2.98095799e+03])

ARRAY SHAPE MANIPULATION



In [59]:
x1=np.array(range(16))
x1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [60]:
x2=x1.reshape( 1,4,4)
x2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [61]:
x3=x2.resize(4,2,2)
x2

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [62]:
y1=np.array(range(5,20,1))
y1

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

 y1=np.array(range(5,20,1))
y1

In [63]:
y2=np.array(range(30,45,1))
y2

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44])

In [64]:
y3=np.hstack([y1,y2])
print(y3)
n=np.shape(y3)
print(n)

[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44]
(30,)


In [65]:
y4=np.vstack([y1,y2])
print(y4)
print(np.shape(y4))

[[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44]]
(2, 15)


In [66]:
y5=y3.reshape(2,15)
y5

array([[ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44]])

In [67]:
y6=np.hsplit(y4,5)        #splits into 3 equal arrays                       

y6                        #its a horizontal split 

[array([[ 5,  6,  7],
        [30, 31, 32]]), array([[ 8,  9, 10],
        [33, 34, 35]]), array([[11, 12, 13],
        [36, 37, 38]]), array([[14, 15, 16],
        [39, 40, 41]]), array([[17, 18, 19],
        [42, 43, 44]])]

In [68]:
import numpy as np
x = np.arange(16.0).reshape(4, 4);
y7=np.vsplit(x,4)             #Vertical split
y7

[array([[0., 1., 2., 3.]]),
 array([[4., 5., 6., 7.]]),
 array([[ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]])]

In [69]:
x = np.arange(16.0).reshape(4, 4)
print(x)
print()
print(np.vsplit(x, 2))
print()
(np.vsplit(x, np.array([3, 6])))

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]

[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]



[array([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]]),
 array([[12., 13., 14., 15.]]),
 array([], shape=(0, 4), dtype=float64)]

In [70]:
#Numpy broad casting
z1=np.array(range(5,50,5))
print(z1)
print()
z2=np.array([0.1,0.2,.3,.1,.4,.6,.7,.3,-0.2])
print(z2)


[ 5 10 15 20 25 30 35 40 45]

[ 0.1  0.2  0.3  0.1  0.4  0.6  0.7  0.3 -0.2]


In [71]:
z1*z2
            #Resultant array broadcasted to float..        

array([ 0.5,  2. ,  4.5,  2. , 10. , 18. , 24.5, 12. , -9. ])

In [72]:
z3=np.array(range(100,111,1))
z3


array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [73]:
z3/-5                      #scalar broadcasting 

array([-20. , -20.2, -20.4, -20.6, -20.8, -21. , -21.2, -21.4, -21.6,
       -21.8, -22. ])

ARRAY TRANSPOSE, INVERSE AND TRACE

In [74]:
z1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [75]:
z4=z1.reshape(3,3)

In [76]:
z4

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [77]:
z4.transpose()              #All rows became columns

array([[ 5, 20, 35],
       [10, 25, 40],
       [15, 30, 45]])

In [78]:
np.linalg.inv(z4)             #Calculates inverse of the matrix

array([[ 3.94064967e+15, -7.88129935e+15,  3.94064967e+15],
       [-7.88129935e+15,  1.57625987e+16, -7.88129935e+15],
       [ 3.94064967e+15, -7.88129935e+15,  3.94064967e+15]])

In [79]:
np.trace(z4)    #obtains sum for principle diagonal elements

75

In [80]:
np.trace(np.eye(5))

5.0

Obtaining eigen value and eigen vector

In [81]:
import numpy as np
v1= np.array([[1 + 1e-9, 0], [0, 1 - 1e-9]])

In [82]:
v1

array([[1., 0.],
       [0., 1.]])

In [83]:
from numpy import linalg as la
la.eig(v1)

(array([1., 1.]), array([[1., 0.],
        [0., 1.]]))

In [84]:
v2=la.eig(np.diag((1, 2, 3)))


In [85]:
v2

(array([1., 2., 3.]), array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))